### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by wingersg** [OctopusSolutionsEngineering/OctopusRecommendationEngine#7] opened 2024-03-12 22:15 UTC
### Octopus version

2023.4.8354

### Octolint version

latest

### What happened

when I run this as a runbook for Default space where there are a lot of projects, I got

panic: runtime error: invalid memory address or nil pointer dereference

### Octolint log output

[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x6f6740]
goroutine 1 [running]:
[github.com/OctopusDeploy/go-octopusdeploy/v2/pkg/feeds.ToFeed(0xc0000f3040)](http://github.com/OctopusDeploy/go-octopusdeploy/v2/pkg/feeds.ToFeed(0xc0000f3040))
    /go/pkg/mod/github.com/!octopus!deploy/go-octopusdeploy/v2@v2.36.3/pkg/feeds/feed_utilities.go:97 +0x6a0
[github.com/OctopusDeploy/go-octopusdeploy/v2/pkg/feeds.ToFeedArray({0xc0001ac000](http://github.com/OctopusDeploy/go-octopusdeploy/v2/pkg/feeds.ToFeedArray(%7B0xc0001ac000), 0xc, 0xc000ad5cc8?})
    /go/pkg/mod/github.com/!octopus!deploy/go-octopusdeploy/v2@v2.36.3/pkg/feeds/feed_utilities.go:188 +0x89
[github.com/OctopusDeploy/go-octopusdeploy/v2/pkg/feeds.(*FeedService).GetAll(0xc00006a4b0)](http://github.com/OctopusDeploy/go-octopusdeploy/v2/pkg/feeds.(*FeedService).GetAll(0xc00006a4b0))
    /go/pkg/mod/github.com/!octopus!deploy/go-octopusdeploy/v2@v2.36.3/pkg/feeds/feed_service.go:85 +0xc7
[github.com/OctopusSolutionsEngineering/OctopusRecommendationEngine/internal/checks/security.OctopusInsecureFeedsCheck.Execute({0xc00014ab00](http://github.com/OctopusSolutionsEngineering/OctopusRecommendationEngine/internal/checks/security.OctopusInsecureFeedsCheck.Execute(%7B0xc00014ab00)?, {0x91cc78?, 0xbf2f18?}})
    /app/internal/checks/security/octopus_insecure_feeds_check.go:30 +0x5f
[github.com/OctopusSolutionsEngineering/OctopusRecommendationEngine/internal/executor.OctopusCheckExecutor.ExecuteChecks.func1()](http://github.com/OctopusSolutionsEngineering/OctopusRecommendationEngine/internal/executor.OctopusCheckExecutor.ExecuteChecks.func1())
    /app/internal/executor/octopus_check_executor.go:28 +0x32
[github.com/avast/retry-go/v4.Do.func1()](http://github.com/avast/retry-go/v4.Do.func1())
    /go/pkg/mod/github.com/avast/retry-go/v4@v4.5.1/retry.go:115 +0x1b
[github.com/avast/retry-go/v4.DoWithData[...]](http://github.com/avast/retry-go/v4.DoWithData[...])(0xc000445d70?, {0xc000445dd0, 0x1, 0x91cea8})
    /go/pkg/mod/github.com/avast/retry-go/v4@v4.5.1/retry.go:179 +0x534
[github.com/avast/retry-go/v4.Do(0xc0000247c0](http://github.com/avast/retry-go/v4.Do(0xc0000247c0)?, {0xc000445dd0?, 0xc00020f800?, 0x91cd18?})
    /go/pkg/mod/github.com/avast/retry-go/v4@v4.5.1/retry.go:118 +0x4a
[github.com/OctopusSolutionsEngineering/OctopusRecommendationEngine/internal/executor.OctopusCheckExecutor.ExecuteChecks({}](http://github.com/OctopusSolutionsEngineering/OctopusRecommendationEngine/internal/executor.OctopusCheckExecutor.ExecuteChecks(%7B%7D), {0xc0002ca000?, 0x1c, 0xbf2f18?}, 0xc000445ef0)
    /app/internal/executor/octopus_check_executor.go:26 +0x13f
main.main()
    /app/cmd/octolint.go:80 +0x3dd

### Reproduction steps

I ran the same on a another space where there are less projects, it worked well.

### More Information

I ran it from octo runbook and also run the same from a linux machine, got the same results.

**Comment by mcasperson** [comment] 2024-03-13 05:52
An initial investigation of the stack trace shows the last code for octolint that is executed is at `octopus_insecure_feeds_check.go:30`, which is this code:

```
targets, err := o.client.Feeds.GetAll()
```

After that the code is in the Octopus Go library. Even if there was an error calling `o.client.Feeds.GetAll()`, the Octopus Go library should have returned that via the `err` parameter.

As a quick first step I can update the Octopus Go library. This may or may not solve the issue, but there are are at least 2 minor version bumps in this library we can use right now.

If this doesn't solve the issue, a deeper dive into the Octopus Go library will be required.

**Comment by mcasperson** [comment] 2024-03-13 06:01
The Go library at version v2.36.3 didn't have support for S3 feeds. @wingersg did your space define a S3 feed by any chance?

The new version of the library v2.38.3 does support the S3 feed. If that was the cause of the issue, the latest commit will resolve it.

**Comment by wingersg** [comment] 2024-03-13 12:04
Hi @mcasperson
Thank you for your reply. yes, could you please update octo go library?as far as I know, the default space has no S3 feed. the container ran for about 3 minutes then exited

**Comment by Clare-Octopus** [comment] 2024-03-13 16:09
Hey @mcasperson,

Funnily enough I was also getting this error in my default space (38 projects in that space). I had an S3 bucket feed and as soon as I deleted it my Octolint runbook worked so it does look like updating the Library will fix this issue.

Happy to chat on slack if you want more information.

**Comment by mcasperson** [comment] 2024-03-14 04:44
@wingersg @Clare-Octopus 

A build with the new Octopus library has been completed, so do you mind trying it again and seeing if it resolves that error?

**Comment by Clare-Octopus** [comment] 2024-03-14 08:40
Hey @mcasperson this works for me now with an S3 Feed re-added! Thank you for fixing that so quickly!

**Comment by wingersg** [comment] 2024-03-14 12:38
Hi @mcasperson 
have you pushed the latest image to docker hub? it is the same when I re-run the job
However, I downloaded the latest binary, and run the following command from wsl, it said: failed to create the Octopus client, when I ran the same from another linux machine, it says /lib64/libc. so.6:version 'GLIBC_2.34' not found

./octolint_linux_amd64 \
    -apiKey API-xxx \
    -url https://octopusurl \
    -space Default

**Comment by mcasperson** [comment] 2024-03-15 00:26
@wingersg 

The image was pushed and is version 1.0.128:

```
$ docker pull octopussamples/octolint
$ docker run octopussamples/octolint -version
Version: 1.0.128
```

You may need to pull down the latest image to make sure you are not using a previously pulled version. Can you confirm that you are running 1.0.128?

**Comment by mcasperson** [comment] 2024-03-15 01:05
Version 1.0.130 has been built with CGO disabled, which should remove the error `/lib64/libc. so.6:version 'GLIBC_2.34' not found`.

**Comment by wingersg** [comment] 2024-03-15 01:26
$` docker run octopussamples/octolint -version`
Version: 1.0.130


```
docker run -t --rm octopussamples/octolint \
    -url https://octopusurl \
    -apiKey "my api key" \
    -space "Default"
```


/panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x6f13dd]

goroutine 1 [running]:
github.com/OctopusDeploy/go-octopusdeploy/v2/pkg/feeds.ToFeed(0xc000383040)
        /go/pkg/mod/github.com/!octopus!deploy/go-octopusdeploy/v2@v2.38.3/pkg/feeds/feed_utilities.go:103 +0x67d
github.com/OctopusDeploy/go-octopusdeploy/v2/pkg/feeds.ToFeedArray({0xc000a4dd80, 0xc, 0xc0008eac30?})
        /go/pkg/mod/github.com/!octopus!deploy/go-octopusdeploy/v2@v2.38.3/pkg/feeds/feed_utilities.go:199 +0x89
github.com/OctopusDeploy/go-octopusdeploy/v2/pkg/feeds.(*FeedService).GetAll(0xc0003702d0)
        /go/pkg/mod/github.com/!octopus!deploy/go-octopusdeploy/v2@v2.38.3/pkg/feeds/feed_service.go:85 +0xbe
github.com/OctopusSolutionsEngineering/OctopusRecommendationEngine/internal/checks/security.OctopusInsecureFeedsCheck.Execute({0xc0000fd608?, {0x90da00?, 0xc2de20?}})
        /app/internal/checks/security/octopus_insecure_feeds_check.go:30 +0x53
github.com/OctopusSolutionsEngineering/OctopusRecommendationEngine/internal/executor.OctopusCheckExecutor.ExecuteChecks.func1()
        /app/internal/executor/octopus_check_executor.go:28 +0x2c
github.com/avast/retry-go/v4.Do.func1()
        /go/pkg/mod/github.com/avast/retry-go/v4@v4.5.1/retry.go:115 +0x13
github.com/avast/retry-go/v4.DoWithData[...](0xc00068fd40?, {0xc00068fdc8, 0x1, 0x90dde8})
        /go/pkg/mod/github.com/avast/retry-go/v4@v4.5.1/retry.go:179 +0x679
github.com/avast/retry-go/v4.Do(0xc00007f980?, {0xc00068fdc8?, 0xc00007f9a0?, 0x90de88?})
        /go/pkg/mod/github.com/avast/retry-go/v4@v4.5.1/retry.go:118 +0x45
github.com/OctopusSolutionsEngineering/OctopusRecommendationEngine/internal/executor.OctopusCheckExecutor.ExecuteChecks({}, {0xc000602700?, 0x90da00?, 0xc2de20?}, 0xc00068ff30)
        /app/internal/executor/octopus_check_executor.go:26 +0x11f
main.main()
        /app/cmd/octolint.go:80 +0x3d4

**Comment by mcasperson** [comment] 2024-03-15 04:00
I think this issue will need to be fixed in the Octopus go library.

The issue is [this line of code](https://github.com/OctopusDeploy/go-octopusdeploy/blob/v2.38.3/pkg/feeds/feed_utilities.go#L103).

For whatever reason the `feed` variable is nil which causes the panic. This should be handled more gracefully.

**Comment by mcasperson** [comment] 2024-03-15 05:28
@wingersg The PR at https://github.com/OctopusDeploy/go-octopusdeploy/pull/243 will address the underlying issue, and the new Go library has been imported into Octolint.

Version 1.0.132 has the latest fixes.

**Comment by wingersg** [comment] 2024-03-15 12:11
Hi @mcasperson I tried again with version 1.0.132, it was finally working, thank you so much!

Some observations:
it took about 30 min to complete a scan , could be due to too many projects?
are there container logs?

**Comment by mcasperson** [comment] 2024-03-17 20:34
@wingersg The scanning time is a known issue for large spaces. There are definitely improvements that can be made here, and this is something on my radar. The most immediate feature is better verbose logging to indicate that the tool is actually doing something on these large spaces.

So there are no logs just yet that you can look at, but a future release will address this.

**Closed by mcasperson** 2024-03-17 20:34 UTC
